# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: '5bcdd13814522047b190a52583be7253712e3a08fd7c9af31ff7f53e97a7e3cf7b83c517e502d3b777ee396d68db5ff2e2e040c2a01cebd7c18f809401edea5c'
  secret_token: '12345678900987654321'
  zoho_password: '02si5ueav9jr'
  twitter_access_key: 'fatG6EcL57A5BIc1SictTFkAL'
  twitter_secret: 'PtLlYmuosbGeJVixL3Wgllw4eq32sLti16B0sEfF1TQhHNEHWN'
  vk_secret: 'OD5FOUzJOiTQF4nzokoI'
  yandex_secret: '09ffb8ccf0444beab92ccf3250462aaf'
  paypal_host: 'https://www.paypal.com'
  app_host: 'http://dbdesigner.net/'
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
